Event QrCode Scanner/Models/ErrorViewModel.cs
namespace Event_QrCode_Scanner.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Event QrCode Scanner/Models/QrCodeData.cs
namespace Event_QrCode_Scanner.Models
{
    public class QrCodeData
    {
        public int Id { get; set; }
        public DateTime Koha_skanimit { get; set; }
        public string? QrCode_Data { get; set; }
    }
}

Event QrCode Scanner/Models/user.cs
namespace Event_QrCode_Scanner.Models
{
    public class User
    {
        public int Id { get; set; }
        public DateTime TimeStamp { get; set; }
        public string FirstLastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string QrCodeUrl { get; set; }

        public ICollection<QrCodeData> QrCodeScans { get; set; }
    }
}

Event QrCode Scanner/Controllers/HomeController.cs
using Event_QrCode_Scanner.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Event_QrCode_Scanner.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Event QrCode Scanner/Controllers/QrCodeController.cs
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Spreadsheet;
using Event_QrCode_Scanner.DbContext;
using Event_QrCode_Scanner.Helper;
using Event_QrCode_Scanner.Models;
using Google.Apis.Auth.OAuth2;
using Google.Apis.Services;
using Google.Apis.Sheets.v4;
using Google.Apis.Sheets.v4.Data;
using Google.Apis.Util.Store;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client.Platforms.Features.DesktopOs.Kerberos;
using System.Net;
using System.Text.RegularExpressions;

namespace Event_QrCode_Scanner.Controllers
{
    public class QrCodeController : Controller
    {
        private readonly ILogger<QrCodeController> _logger;
        private readonly Konteksti _context;
        //private readonly GoogleSheetsService _googleSheetsService;

        public QrCodeController(ILogger<QrCodeController> logger, Konteksti context)
        {
            _logger = logger;
            _context = context;
            //_googleSheetsService = googleSheetsService;
        }

        public IActionResult Index()
        {
            return View();
        }

        // ruan QR kodin ne databaze nese nuk eshte prezent
        [HttpPost]
        public IActionResult SaveQRCodeData(string qrData)
        {
            if (!qrData.ToLower().Contains("-1111-") || !qrData.ToLower().Contains("-2222-"))
            {
                return StatusCode(503);
            }

            // Kerko ne bazen e te dhenave per te pare nese ekziston nje QR kod i njejte
            var existingQrCodeData = _context.QrCodeData.FirstOrDefault(q => q.QrCode_Data == qrData);

            // Nese ekziston, kthe nje pergjigje gabimi "Bad Request"
            if (existingQrCodeData != null)
            {
                return StatusCode(504);
            }

            try
            {
                // krijo nje objekt te ri `QrCodeData` per te ruajtur te dhenat e QR kodit dhe kohen e skanimit
                var newQrCodeData = new QrCodeData
                {
                    QrCode_Data = qrData,
                    Koha_skanimit = DateTime.Now
                };

                // Shto te dhenat e reja ne bazen e te dhenave
                _context.QrCodeData.Add(newQrCodeData);
                _context.SaveChanges(); // Ruaj ndryshimet ne bazen e te dhenave

                // Kthe nje pergjigje "OK" me nje mesazh suksesi
                return Ok("QR Kodi eshte ruajtur ne databaze.");
            }
            catch (Exception)
            {
                return StatusCode(500, "Ndodhi nje gabim ju lutem provoni me vone");
            }
        }

        // merr si liste nga databaza per ti shfaqur 
        [HttpGet]
        public IActionResult GetScannedQRCodeData()
        {
            var qrCodeDataList = _context.QrCodeData.ToList();
            return Json(qrCodeDataList);
        }

        // perditson excel file me te dhenat nga databaza
        [HttpPost]
        public IActionResult UpdateSpreadsheet()
        {
            try
            {
                string path;
                string fileName = "\\Konferenca Dev Ops 2024 (Responses).xlsx";

                GetAndSaveDownloadsPath(out path);
                string fullPath = Path.Combine(path + fileName);

                var userIds = _context.QrCodeData.Select(q => q.QrCode_Data).ToList();
                bool nderrimetBera = false; 

                DownloadTheExcelFile(path, fileName);
                
                using (var workbook = new XLWorkbook(fullPath))
                {
                    var worksheet = workbook.Worksheet(1); // sheet 1
                    var rows = worksheet.RangeUsed().RowsUsed().Skip(1); // kalo rreshtin header 

                    foreach (var row in rows)
                    {
                        string userId = row.Cell(1).GetValue<string>(); // merr vleren prej kolones A (userID)
                        string status = row.Cell(7).GetValue<string>(); // merr vleren prej kolones G (status)

                        if (string.IsNullOrEmpty(status))
                        {
                            row.Cell(7).SetValue("Regjistruar"); // nese nuk ka vlere statusi by default "Regjistruar"
                            nderrimetBera = true; // Flag change
                        }
                        else if (status != "Pjesmarres" && userIds.Contains(userId))
                        {
                            row.Cell(7).SetValue("Pjesmarres"); // jepi vleren "Pjesmarres" nese userID eshte gjet edhe nuk eshte i ndrruar
                            nderrimetBera = true; // Flag change
                        }
                    }
                    workbook.Save();
                }

                if (!nderrimetBera)
                {
                    // nese nuk ka ndrrime shfaq SweetAlert info
                    return Content("<script>Swal.fire('Info', 'Lista eshte e perditsuar', 'info').then(() => window.location.href = '/');</script>", "text/html");
                }
                return Ok("Lista u validua me sukses");
            }            
            catch (Exception)
            {
                // kthe error nese file nuk gjindet
                return StatusCode(500, new { message = "Deshtim i validimit ju lutem provoni me vone!" });
            }
        }

        public void DownloadTheExcelFile(string path, string fileName)
        {
            string exportUrl = "https://docs.google.com/spreadsheets/d/1QkJ54EMfBbD1JkKlScLazhXBH4WJNAkjBVur-MoKfhc/export?format=xlsx";
            string downloadedFilePath = Path.Combine(path + fileName);

            using (var client = new WebClient())
            {                
                if (!FileHelper.FileExists(downloadedFilePath))
                {
                    client.DownloadFile(exportUrl, downloadedFilePath); 
                    //FileHelper.DeleteFile(downloadedFilePath);
                }
            } 
        }

        // Merr shtegun e folderit "Downloads" te perdoruesit
        public static void GetAndSaveDownloadsPath(out string path)
        {
            path = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile) + "\\Downloads";
        }
    }
}

Event QrCode Scanner/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <div class="button-container">
        <button onclick="setTimeout(function() { window.location.href = '@Url.Action("Index", "QrCode")'; }, 400)">
            <div class="svg-wrapper-1">
                <div class="svg-wrapper">
                    <svg
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 24 24"
                        width="24"
                        height="24"
                    >
                        <path fill="none" d="M0 0h24v24H0z"></path>
                        <path
                            fill="currentColor"
                            d="M1.946 9.315c-.522-.174-.527-.455.01-.634l19.087-6.362c.529-.176.832.12.684.638l-5.454 19.086c-.15.529-.455.547-.679.045L12 14l6-8-8 6-8.054-2.685z"
                        ></path>
                    </svg>
                </div>
            </div>
            <span>Scanner</span>
        </button>
    </div>
</div>


<style>
    .button-container { /* Parent container */
        display: flex;
        justify-content: center; 
    }
    button {
        font-family: inherit;
        font-size: 20px;
        background: royalblue;
        color: white;
        padding: 0.7em 1em;
        padding-left: 0.9em;
        display: flex;
        align-items: center;
        border: none;
        border-radius: 16px;
        overflow: hidden;
        transition: all 0.2s;
        cursor: pointer;
    }

    button span {
        display: block;
        margin-left: 0.3em;
        transition: all 0.3s ease-in-out;
    }

    button svg {
        display: block;
        transform-origin: center center;
        transition: transform 0.3s ease-in-out;
    }

    button:hover .svg-wrapper {
        animation: fly-1 0.6s ease-in-out infinite alternate;
    }

    button:hover svg {
        transform: translateX(1.2em) rotate(45deg) scale(1.1);
    }

    button:hover span {
        transform: translateX(5em);
    }

    button:active {
        transform: scale(0.95);
    }

    @@keyframes fly-1 {
        from {
            transform: translateY(0.1em);
        }

        to {
            transform: translateY(-0.1em);
        }
    }
</style>

Event QrCode Scanner/Views/QrCode/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <h1 class="mt-5 mb-4">Skaneri i QR kodit</h1>
        <div class="d-flex justify-content-between mb-3">
            <div>
                <button id="startButton" class="btn btn-primary me-2">Starto kameren</button>
                <button id="stopButton" class="btn btn-danger">Ndalo kameren</button>
            </div>
            <button id="compareButton" class="btn btn-info">Perditeso Listen</button>
        </div>
        <div class="row mt-3">
            <div class="col-md-6">
                <video id="videoElement" class="w-100" width="100%" height="auto" autoplay playsinline></video>
            </div>
            <div class="col-md-6">
                <h3>Te dhenat e QR kodit</h3>
                <div class="table-responsive">
                    <table id="qrDataTable" class="table">
                        <thead>
                            <tr>
                                <th class="col-md-2">ID</th>
                                <th class="col-md-4">Koha e Skanimit</th>
                                <th class="col-md-6">QR Kodi Dekoduar</th>
                            </tr>
                        </thead>
                        <tbody>
                        <!-- te dhenat do te popullohen ketu -->
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jsqr/dist/jsQR.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script>
        const video = document.getElementById('videoElement');
        const startButton = document.getElementById('startButton');
        const stopButton = document.getElementById('stopButton');
        const compareButton = document.getElementById('compareButton');
        let stream;

        perditsoQRkodListen();

        startButton.addEventListener('click', function (event) {
            event.preventDefault(); // parandaloni sjelljen default
            startoKameren();
        });

        stopButton.addEventListener('click', ndaloKameren);
        compareButton.addEventListener('click', krahasoQRkodin);

        function startoKameren() {
            // specifikimi i kufizimet per getUserMedia
            const kufizimet = {
                video: {
                    facingMode: { ideal: 'environment' } // perdor kameren e pasme nese e mundur
                }
            };
            navigator.mediaDevices.getUserMedia(kufizimet)
                .then(neStartKamera)
                .catch(onCameraError);
        }


        function neStartKamera(cameraStream) {
            stream = cameraStream;
            video.srcObject = stream;
            video.play(); // fillo videon
            // degjues i eventit per 'loadedmetadata' i elementtit te videos
            video.addEventListener('loadedmetadata', function () {
                // thirr per kontrollim te qr kodit
                requestAnimationFrame(kontrolloQRkod);
            });
        }

        // ndalo kameren
        function ndaloKameren() {
            if (stream) {
                stream.getTracks().forEach(track => {
                    track.stop();
                });
            }
        }

        // krahaso listen ne databaze me ate ne excel
        function krahasoQRkodin() {
            $.ajax({
                type: 'POST',
                url: '/QrCode/UpdateSpreadsheet',
                success: function (response) {
                    showNotification('success', 'Success!', response);
                    Swal.fire({
                        icon: 'info',
                        title: 'Info',
                        text: 'Lista eshte e perditesuar',
                        showCloseButton: false,
                        timer: 2000
                    });
                },
                error: function (error) {                   
                    if (error.status === 500) { 
                        const errorMessage = error.responseJSON.message; // Merr mesazhin e gabimit nga përgjigja JSON
                        showNotification('error', 'Gabim!', errorMessage); // Shfaq njoftimin e gabimit me SweetAlert2
                    } else {                      
                        showNotification('error', 'Gabim!', 'Një gabim ka ndodhur.'); // Mesazh i përgjithshëm gabimi
                    }                    
                }
            });
        }

        let lastScanTime = 0;
        const scanDelay = 2200; // vonesa ndermjet skanimeve (milisekonda)

        function kontrolloQRkod() {
            console.log("Kontrollimi per QR kod...");

            // llogaritni kohen e kaluar nga skanimi i fundit
            const currentTime = performance.now();
            const elapsedTime = currentTime - lastScanTime;

            // Kontrolloni nese ka kaluar kohe e mjaftueshme per te kryer nje tjeter skanim
            if (elapsedTime >= scanDelay) {
                const canvas = document.createElement('canvas');
                canvas.width = video.videoWidth;
                canvas.height = video.videoHeight;
                const context = canvas.getContext('2d');
                context.drawImage(video, 0, 0, canvas.width, canvas.height);

                const imageData = context.getImageData(0, 0, canvas.width, canvas.height);
                const code = jsQR(imageData.data, imageData.width, imageData.height);

                if (code && code.data) {
                    console.log("QR kod u gjet:", code.data);
                    const qrData = code.data;
                    ruajQRkodData(qrData);
                } else {
                    console.log("QR kod nuk gjindet");
                }

                // Perditeso kohen e fundit te skanimit
                lastScanTime = currentTime;
            }

            requestAnimationFrame(kontrolloQRkod);
        }

        function ruajQRkodData(qrData) {
            console.log("Te dhenat e QR kodi:", qrData);
            $.ajax({
                type: 'POST',
                url: '/QrCode/SaveQRCodeData',
                data: { qrData },
                success: function (response) {
                    showNotification('success', 'Success!', response);
                    perditsoQRkodListen();
                },
                error: function (error) {
                    debugger;
                    if (error.status === 503) {                       
                        showNotification('error', 'Gabim!', 'QR Kodi nuk është në formatin e duhur.'); 
                    }
                    else if(error.status === 504){
                        showNotification('error', 'Gabim!', ' Ky QR Kod është i përdorur.');
                    }
                    else {
                        showNotification('error', 'Gabim!', 'Një gabim ka ndodhur.'); // Mesazh i përgjithshëm gabimi
                    }
                }
            });
        }

        function perditsoQRkodListen() {
            $.ajax({
                type: 'GET',
                url: '/QrCode/GetScannedQRCodeData',
                success: function (data) {
                    const tbody = $('#qrDataTable tbody');
                    tbody.empty();

                    data.forEach(qrCodeData => {
                        const row = $('<tr>').append(
                            $('<td>').text(qrCodeData.id),
                            $('<td>').text(new Date(qrCodeData.koha_skanimit).toLocaleString()),
                            $('<td>').text(qrCodeData.qrCode_Data)
                        );
                        tbody.append(row);
                    });
                },
                error: function (error) {
                    console.error('Gabim ne nxjerrjen e te dhenave te QR kodit:', error);
                }
            });
        }

        function onCameraError(error) {
            console.error('Gabim ne qasjen ne kamere:', error);
        }

        function showNotification(icon, title, message) {
            Swal.fire({
                icon: icon,
                title: title,
                text: message,
                showCloseButton: false,
                timer: 2000
            });
        }
    </script>


</body>
</html>

Event QrCode Scanner/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Event_QrCode_Scanner</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Event_QrCode_Scanner.styles.css" asp-append-version="true" />
</head>
<body class="d-flex flex-column">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Event QrCode Scanner</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="QrCode" asp-action="Index">Qr Kodi</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
<div class="container">
    <main role="main">
        @RenderBody()
    </main>
</div>


  @*   <footer class="border-top footer text-muted mb-4 fixed-bottom"> 

        <div class="container">
            &copy; 2024 - Event_QrCode_Scanner - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>